// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/spidernet-io/egressgateway/pkg/k8s/apis/egressgateway.spidernet.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// EgressGatewayRuleLister helps list EgressGatewayRules.
// All objects returned here must be treated as read-only.
type EgressGatewayRuleLister interface {
	// List lists all EgressGatewayRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.EgressGatewayRule, err error)
	// Get retrieves the EgressGatewayRule from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.EgressGatewayRule, error)
	EgressGatewayRuleListerExpansion
}

// egressGatewayRuleLister implements the EgressGatewayRuleLister interface.
type egressGatewayRuleLister struct {
	indexer cache.Indexer
}

// NewEgressGatewayRuleLister returns a new EgressGatewayRuleLister.
func NewEgressGatewayRuleLister(indexer cache.Indexer) EgressGatewayRuleLister {
	return &egressGatewayRuleLister{indexer: indexer}
}

// List lists all EgressGatewayRules in the indexer.
func (s *egressGatewayRuleLister) List(selector labels.Selector) (ret []*v1.EgressGatewayRule, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.EgressGatewayRule))
	})
	return ret, err
}

// Get retrieves the EgressGatewayRule from the index for a given name.
func (s *egressGatewayRuleLister) Get(name string) (*v1.EgressGatewayRule, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("egressgatewayrule"), name)
	}
	return obj.(*v1.EgressGatewayRule), nil
}
