// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/spidernet-io/egressgateway/pkg/k8s/apis/egressgateway.spidernet.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// EgressGatewayNodeLister helps list EgressGatewayNodes.
// All objects returned here must be treated as read-only.
type EgressGatewayNodeLister interface {
	// List lists all EgressGatewayNodes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.EgressGatewayNode, err error)
	// Get retrieves the EgressGatewayNode from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.EgressGatewayNode, error)
	EgressGatewayNodeListerExpansion
}

// egressGatewayNodeLister implements the EgressGatewayNodeLister interface.
type egressGatewayNodeLister struct {
	indexer cache.Indexer
}

// NewEgressGatewayNodeLister returns a new EgressGatewayNodeLister.
func NewEgressGatewayNodeLister(indexer cache.Indexer) EgressGatewayNodeLister {
	return &egressGatewayNodeLister{indexer: indexer}
}

// List lists all EgressGatewayNodes in the indexer.
func (s *egressGatewayNodeLister) List(selector labels.Selector) (ret []*v1.EgressGatewayNode, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.EgressGatewayNode))
	})
	return ret, err
}

// Get retrieves the EgressGatewayNode from the index for a given name.
func (s *egressGatewayNodeLister) Get(name string) (*v1.EgressGatewayNode, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("egressgatewaynode"), name)
	}
	return obj.(*v1.EgressGatewayNode), nil
}
