// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// EgressGatewayNodeListerExpansion allows custom methods to be added to
// EgressGatewayNodeLister.
type EgressGatewayNodeListerExpansion interface{}

// EgressGatewayPolicyListerExpansion allows custom methods to be added to
// EgressGatewayPolicyLister.
type EgressGatewayPolicyListerExpansion interface{}

// EgressNodeListerExpansion allows custom methods to be added to
// EgressNodeLister.
type EgressNodeListerExpansion interface{}
