// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// EgressGatewayListerExpansion allows custom methods to be added to
// EgressGatewayLister.
type EgressGatewayListerExpansion interface{}

// EgressGatewayPolicyListerExpansion allows custom methods to be added to
// EgressGatewayPolicyLister.
type EgressGatewayPolicyListerExpansion interface{}

// EgressNodeListerExpansion allows custom methods to be added to
// EgressNodeLister.
type EgressNodeListerExpansion interface{}
