// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// EgressGatewayNodeListerExpansion allows custom methods to be added to
// EgressGatewayNodeLister.
type EgressGatewayNodeListerExpansion interface{}

// EgressGatewayRuleListerExpansion allows custom methods to be added to
// EgressGatewayRuleLister.
type EgressGatewayRuleListerExpansion interface{}

// NodeListerExpansion allows custom methods to be added to
// NodeLister.
type NodeListerExpansion interface{}
