// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	egressgatewayspidernetiov1 "github.com/spidernet-io/egressgateway/pkg/k8s/apis/egressgateway.spidernet.io/v1"
	versioned "github.com/spidernet-io/egressgateway/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/spidernet-io/egressgateway/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1 "github.com/spidernet-io/egressgateway/pkg/k8s/client/listers/egressgateway.spidernet.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EgressGatewayRuleInformer provides access to a shared informer and lister for
// EgressGatewayRules.
type EgressGatewayRuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.EgressGatewayRuleLister
}

type egressGatewayRuleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewEgressGatewayRuleInformer constructs a new informer for EgressGatewayRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEgressGatewayRuleInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEgressGatewayRuleInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredEgressGatewayRuleInformer constructs a new informer for EgressGatewayRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEgressGatewayRuleInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EgressgatewayV1().EgressGatewayRules().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EgressgatewayV1().EgressGatewayRules().Watch(context.TODO(), options)
			},
		},
		&egressgatewayspidernetiov1.EgressGatewayRule{},
		resyncPeriod,
		indexers,
	)
}

func (f *egressGatewayRuleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEgressGatewayRuleInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *egressGatewayRuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&egressgatewayspidernetiov1.EgressGatewayRule{}, f.defaultInformer)
}

func (f *egressGatewayRuleInformer) Lister() v1.EgressGatewayRuleLister {
	return v1.NewEgressGatewayRuleLister(f.Informer().GetIndexer())
}
