// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	egressgatewayspidernetiov1 "github.com/spidernet-io/egressgateway/pkg/k8s/apis/egressgateway.spidernet.io/v1"
	versioned "github.com/spidernet-io/egressgateway/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/spidernet-io/egressgateway/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1 "github.com/spidernet-io/egressgateway/pkg/k8s/client/listers/egressgateway.spidernet.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EgressGatewayPolicyInformer provides access to a shared informer and lister for
// EgressGatewayPolicies.
type EgressGatewayPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.EgressGatewayPolicyLister
}

type egressGatewayPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewEgressGatewayPolicyInformer constructs a new informer for EgressGatewayPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEgressGatewayPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEgressGatewayPolicyInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredEgressGatewayPolicyInformer constructs a new informer for EgressGatewayPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEgressGatewayPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EgressgatewayV1().EgressGatewayPolicies().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EgressgatewayV1().EgressGatewayPolicies().Watch(context.TODO(), options)
			},
		},
		&egressgatewayspidernetiov1.EgressGatewayPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *egressGatewayPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEgressGatewayPolicyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *egressGatewayPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&egressgatewayspidernetiov1.EgressGatewayPolicy{}, f.defaultInformer)
}

func (f *egressGatewayPolicyInformer) Lister() v1.EgressGatewayPolicyLister {
	return v1.NewEgressGatewayPolicyLister(f.Informer().GetIndexer())
}
