// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/spidernet-io/egressgateway/pkg/k8s/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// EgressGatewayNodes returns a EgressGatewayNodeInformer.
	EgressGatewayNodes() EgressGatewayNodeInformer
	// EgressGatewayPolicies returns a EgressGatewayPolicyInformer.
	EgressGatewayPolicies() EgressGatewayPolicyInformer
	// EgressNodes returns a EgressNodeInformer.
	EgressNodes() EgressNodeInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// EgressGatewayNodes returns a EgressGatewayNodeInformer.
func (v *version) EgressGatewayNodes() EgressGatewayNodeInformer {
	return &egressGatewayNodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// EgressGatewayPolicies returns a EgressGatewayPolicyInformer.
func (v *version) EgressGatewayPolicies() EgressGatewayPolicyInformer {
	return &egressGatewayPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// EgressNodes returns a EgressNodeInformer.
func (v *version) EgressNodes() EgressNodeInformer {
	return &egressNodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
