apiVersion: apps/v1
kind: DaemonSet
metadata:
  name:  {{ .Values.agent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.egressgatewayAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "project.egressgatewayAgent.selectorLabels" . | nindent 6 }}
  {{- with .Values.agent.updateStrategy }}
  updateStrategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- if or .Values.agent.podAnnotations .Values.global.commonAnnotations }}
      annotations:
        {{- if .Values.global.commonAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.agent.podAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.agent.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "project.egressgatewayAgent.selectorLabels" . | nindent 8 }}
        {{- if .Values.global.commonLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.agent.podLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.agent.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.agent.image.imagePullSecrets }}
      imagePullSecrets:
      {{- with .Values.agent.image.imagePullSecrets }}
      {{- toYaml . | trim | nindent 6 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Values.agent.name | trunc 63 | trimSuffix "-" }}
      priorityClassName: {{ default "system-node-critical" .Values.agent.priorityClassName }}
      {{- if .Values.agent.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- else }}
      hostNetwork: false
      dnsPolicy: ClusterFirst
      {{- end }}
      restartPolicy: Always
      {{- with .Values.agent.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.agent.affinity }}
      affinity:
      {{- include "tplvalues.render" (dict "value" .Values.agent.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              {{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.Version -}}
              # Compatible with Kubernetes 1.12.x and 1.13.x
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.agent.name | trunc 63 | trimSuffix "-" }}
          securityContext:
            privileged: true
          image: {{ include "project.egressgatewayAgent.image" . | quote }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          command:
            - {{ .Values.agent.cmdBinName }}
          {{- with .Values.agent.extraArgs }}
          {{- toYaml . | trim | nindent 8 }}
          {{- end }}
          {{- if .Values.agent.prometheus.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.agent.prometheus.port }}
              protocol: TCP
          {{- end }}
          {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.Version }}
          startupProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.agent.healthServer.port }}
              scheme: HTTP
            failureThreshold: {{ .Values.agent.healthServer.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.agent.healthServer.startupProbe.periodSeconds }}
            successThreshold: 1
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.agent.healthServer.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: {{ .Values.agent.healthServer.livenessProbe.periodSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.agent.healthServer.livenessProbe.failureThreshold }}
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.agent.healthServer.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.agent.healthServer.readinessProbe.periodSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.agent.healthServer.readinessProbe.failureThreshold }}
            timeoutSeconds: 5
          {{- with .Values.agent.resources }}
          resources:
          {{- toYaml . | trim | nindent 12 }}
          {{- end }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.agent.debug.logLevel | quote }}
            - name: LOG_USE_DEV_MODE
              value: {{ .Values.agent.debug.logUseDevMode | quote }}
            - name: LOG_WITH_CALLER
              value: {{ .Values.agent.debug.logWithCaller | quote }}
            - name: LOG_ENCODER
              value: {{ .Values.agent.debug.logEncoder | quote }}
            {{ if .Values.agent.prometheus.enabled }}
            - name: METRICS_BIND_ADDRESS
              value: :{{ .Values.agent.prometheus.port }}
            {{ end }}
            - name: HEALTH_PROBE_BIND_ADDRESS
              value: :{{ .Values.agent.healthServer.port }}
            - name: PYROSCOPE_SERVER_ADDR
              value: {{ .Values.agent.debug.pyroscopeServerAddr | quote }}
            - name: GOPS_PORT
              value: {{ .Values.agent.debug.gopsPort | quote }}
            - name: CONFIGMAP_PATH
              value: "/tmp/config-map/conf.yml"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            {{- with .Values.agent.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.agent.securityContext }}
          securityContext:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
            - mountPath: /run/xtables.lock
              name: xtables-lock
            - name: config-path
              mountPath: /tmp/config-map
              readOnly: true
            {{- if .Values.agent.extraVolumes }}
            {{- include "tplvalues.render" ( dict "value" .Values.agent.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
      volumes:
        # To read the configuration from the config map
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
        - name: config-path
          configMap:
            defaultMode: 0400
            name: {{ .Values.global.configName }}
      {{- if .Values.agent.extraVolumeMounts }}
      {{- include "tplvalues.render" ( dict "value" .Values.agent.extraVolumeMounts "context" $ ) | nindent 6 }}
      {{- end }}
