// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package healthy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetHealthyLivenessReader is a Reader for the GetHealthyLiveness structure.
type GetHealthyLivenessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHealthyLivenessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHealthyLivenessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetHealthyLivenessInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHealthyLivenessOK creates a GetHealthyLivenessOK with default headers values
func NewGetHealthyLivenessOK() *GetHealthyLivenessOK {
	return &GetHealthyLivenessOK{}
}

/*
GetHealthyLivenessOK describes a response with status code 200, with default header values.

Success
*/
type GetHealthyLivenessOK struct {
}

func (o *GetHealthyLivenessOK) Error() string {
	return fmt.Sprintf("[GET /healthy/liveness][%d] getHealthyLivenessOK ", 200)
}

func (o *GetHealthyLivenessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHealthyLivenessInternalServerError creates a GetHealthyLivenessInternalServerError with default headers values
func NewGetHealthyLivenessInternalServerError() *GetHealthyLivenessInternalServerError {
	return &GetHealthyLivenessInternalServerError{}
}

/*
GetHealthyLivenessInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type GetHealthyLivenessInternalServerError struct {
}

func (o *GetHealthyLivenessInternalServerError) Error() string {
	return fmt.Sprintf("[GET /healthy/liveness][%d] getHealthyLivenessInternalServerError ", 500)
}

func (o *GetHealthyLivenessInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
