// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	egressgatewayspidernetiov1 "github.com/spidernet-io/egressgateway/pkg/k8s/apis/egressgateway.spidernet.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEgressGatewayNodes implements EgressGatewayNodeInterface
type FakeEgressGatewayNodes struct {
	Fake *FakeEgressgatewayV1
}

var egressgatewaynodesResource = schema.GroupVersionResource{Group: "egressgateway.spidernet.io", Version: "v1", Resource: "egressgatewaynodes"}

var egressgatewaynodesKind = schema.GroupVersionKind{Group: "egressgateway.spidernet.io", Version: "v1", Kind: "EgressGatewayNode"}

// Get takes name of the egressGatewayNode, and returns the corresponding egressGatewayNode object, and an error if there is any.
func (c *FakeEgressGatewayNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *egressgatewayspidernetiov1.EgressGatewayNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(egressgatewaynodesResource, name), &egressgatewayspidernetiov1.EgressGatewayNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGatewayNode), err
}

// List takes label and field selectors, and returns the list of EgressGatewayNodes that match those selectors.
func (c *FakeEgressGatewayNodes) List(ctx context.Context, opts v1.ListOptions) (result *egressgatewayspidernetiov1.EgressGatewayNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(egressgatewaynodesResource, egressgatewaynodesKind, opts), &egressgatewayspidernetiov1.EgressGatewayNodeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &egressgatewayspidernetiov1.EgressGatewayNodeList{ListMeta: obj.(*egressgatewayspidernetiov1.EgressGatewayNodeList).ListMeta}
	for _, item := range obj.(*egressgatewayspidernetiov1.EgressGatewayNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested egressGatewayNodes.
func (c *FakeEgressGatewayNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(egressgatewaynodesResource, opts))
}

// Create takes the representation of a egressGatewayNode and creates it.  Returns the server's representation of the egressGatewayNode, and an error, if there is any.
func (c *FakeEgressGatewayNodes) Create(ctx context.Context, egressGatewayNode *egressgatewayspidernetiov1.EgressGatewayNode, opts v1.CreateOptions) (result *egressgatewayspidernetiov1.EgressGatewayNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(egressgatewaynodesResource, egressGatewayNode), &egressgatewayspidernetiov1.EgressGatewayNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGatewayNode), err
}

// Update takes the representation of a egressGatewayNode and updates it. Returns the server's representation of the egressGatewayNode, and an error, if there is any.
func (c *FakeEgressGatewayNodes) Update(ctx context.Context, egressGatewayNode *egressgatewayspidernetiov1.EgressGatewayNode, opts v1.UpdateOptions) (result *egressgatewayspidernetiov1.EgressGatewayNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(egressgatewaynodesResource, egressGatewayNode), &egressgatewayspidernetiov1.EgressGatewayNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGatewayNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEgressGatewayNodes) UpdateStatus(ctx context.Context, egressGatewayNode *egressgatewayspidernetiov1.EgressGatewayNode, opts v1.UpdateOptions) (*egressgatewayspidernetiov1.EgressGatewayNode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(egressgatewaynodesResource, "status", egressGatewayNode), &egressgatewayspidernetiov1.EgressGatewayNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGatewayNode), err
}

// Delete takes name of the egressGatewayNode and deletes it. Returns an error if one occurs.
func (c *FakeEgressGatewayNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(egressgatewaynodesResource, name, opts), &egressgatewayspidernetiov1.EgressGatewayNode{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEgressGatewayNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(egressgatewaynodesResource, listOpts)

	_, err := c.Fake.Invokes(action, &egressgatewayspidernetiov1.EgressGatewayNodeList{})
	return err
}

// Patch applies the patch and returns the patched egressGatewayNode.
func (c *FakeEgressGatewayNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *egressgatewayspidernetiov1.EgressGatewayNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(egressgatewaynodesResource, name, pt, data, subresources...), &egressgatewayspidernetiov1.EgressGatewayNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGatewayNode), err
}
