// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	egressgatewayspidernetiov1 "github.com/spidernet-io/egressgateway/pkg/k8s/apis/egressgateway.spidernet.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEgressGatewayRules implements EgressGatewayRuleInterface
type FakeEgressGatewayRules struct {
	Fake *FakeEgressgatewayV1
}

var egressgatewayrulesResource = schema.GroupVersionResource{Group: "egressgateway.spidernet.io", Version: "v1", Resource: "egressgatewayrules"}

var egressgatewayrulesKind = schema.GroupVersionKind{Group: "egressgateway.spidernet.io", Version: "v1", Kind: "EgressGatewayRule"}

// Get takes name of the egressGatewayRule, and returns the corresponding egressGatewayRule object, and an error if there is any.
func (c *FakeEgressGatewayRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *egressgatewayspidernetiov1.EgressGatewayRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(egressgatewayrulesResource, name), &egressgatewayspidernetiov1.EgressGatewayRule{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGatewayRule), err
}

// List takes label and field selectors, and returns the list of EgressGatewayRules that match those selectors.
func (c *FakeEgressGatewayRules) List(ctx context.Context, opts v1.ListOptions) (result *egressgatewayspidernetiov1.EgressGatewayRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(egressgatewayrulesResource, egressgatewayrulesKind, opts), &egressgatewayspidernetiov1.EgressGatewayRuleList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &egressgatewayspidernetiov1.EgressGatewayRuleList{ListMeta: obj.(*egressgatewayspidernetiov1.EgressGatewayRuleList).ListMeta}
	for _, item := range obj.(*egressgatewayspidernetiov1.EgressGatewayRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested egressGatewayRules.
func (c *FakeEgressGatewayRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(egressgatewayrulesResource, opts))
}

// Create takes the representation of a egressGatewayRule and creates it.  Returns the server's representation of the egressGatewayRule, and an error, if there is any.
func (c *FakeEgressGatewayRules) Create(ctx context.Context, egressGatewayRule *egressgatewayspidernetiov1.EgressGatewayRule, opts v1.CreateOptions) (result *egressgatewayspidernetiov1.EgressGatewayRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(egressgatewayrulesResource, egressGatewayRule), &egressgatewayspidernetiov1.EgressGatewayRule{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGatewayRule), err
}

// Update takes the representation of a egressGatewayRule and updates it. Returns the server's representation of the egressGatewayRule, and an error, if there is any.
func (c *FakeEgressGatewayRules) Update(ctx context.Context, egressGatewayRule *egressgatewayspidernetiov1.EgressGatewayRule, opts v1.UpdateOptions) (result *egressgatewayspidernetiov1.EgressGatewayRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(egressgatewayrulesResource, egressGatewayRule), &egressgatewayspidernetiov1.EgressGatewayRule{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGatewayRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEgressGatewayRules) UpdateStatus(ctx context.Context, egressGatewayRule *egressgatewayspidernetiov1.EgressGatewayRule, opts v1.UpdateOptions) (*egressgatewayspidernetiov1.EgressGatewayRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(egressgatewayrulesResource, "status", egressGatewayRule), &egressgatewayspidernetiov1.EgressGatewayRule{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGatewayRule), err
}

// Delete takes name of the egressGatewayRule and deletes it. Returns an error if one occurs.
func (c *FakeEgressGatewayRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(egressgatewayrulesResource, name, opts), &egressgatewayspidernetiov1.EgressGatewayRule{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEgressGatewayRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(egressgatewayrulesResource, listOpts)

	_, err := c.Fake.Invokes(action, &egressgatewayspidernetiov1.EgressGatewayRuleList{})
	return err
}

// Patch applies the patch and returns the patched egressGatewayRule.
func (c *FakeEgressGatewayRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *egressgatewayspidernetiov1.EgressGatewayRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(egressgatewayrulesResource, name, pt, data, subresources...), &egressgatewayspidernetiov1.EgressGatewayRule{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGatewayRule), err
}
