// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	egressgatewayspidernetiov1 "github.com/spidernet-io/egressgateway/pkg/k8s/apis/egressgateway.spidernet.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEgressGateways implements EgressGatewayInterface
type FakeEgressGateways struct {
	Fake *FakeEgressgatewayV1
}

var egressgatewaysResource = schema.GroupVersionResource{Group: "egressgateway.spidernet.io", Version: "v1", Resource: "egressgateways"}

var egressgatewaysKind = schema.GroupVersionKind{Group: "egressgateway.spidernet.io", Version: "v1", Kind: "EgressGateway"}

// Get takes name of the egressGateway, and returns the corresponding egressGateway object, and an error if there is any.
func (c *FakeEgressGateways) Get(ctx context.Context, name string, options v1.GetOptions) (result *egressgatewayspidernetiov1.EgressGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(egressgatewaysResource, name), &egressgatewayspidernetiov1.EgressGateway{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGateway), err
}

// List takes label and field selectors, and returns the list of EgressGateways that match those selectors.
func (c *FakeEgressGateways) List(ctx context.Context, opts v1.ListOptions) (result *egressgatewayspidernetiov1.EgressGatewayList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(egressgatewaysResource, egressgatewaysKind, opts), &egressgatewayspidernetiov1.EgressGatewayList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &egressgatewayspidernetiov1.EgressGatewayList{ListMeta: obj.(*egressgatewayspidernetiov1.EgressGatewayList).ListMeta}
	for _, item := range obj.(*egressgatewayspidernetiov1.EgressGatewayList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested egressGateways.
func (c *FakeEgressGateways) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(egressgatewaysResource, opts))
}

// Create takes the representation of a egressGateway and creates it.  Returns the server's representation of the egressGateway, and an error, if there is any.
func (c *FakeEgressGateways) Create(ctx context.Context, egressGateway *egressgatewayspidernetiov1.EgressGateway, opts v1.CreateOptions) (result *egressgatewayspidernetiov1.EgressGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(egressgatewaysResource, egressGateway), &egressgatewayspidernetiov1.EgressGateway{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGateway), err
}

// Update takes the representation of a egressGateway and updates it. Returns the server's representation of the egressGateway, and an error, if there is any.
func (c *FakeEgressGateways) Update(ctx context.Context, egressGateway *egressgatewayspidernetiov1.EgressGateway, opts v1.UpdateOptions) (result *egressgatewayspidernetiov1.EgressGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(egressgatewaysResource, egressGateway), &egressgatewayspidernetiov1.EgressGateway{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGateway), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEgressGateways) UpdateStatus(ctx context.Context, egressGateway *egressgatewayspidernetiov1.EgressGateway, opts v1.UpdateOptions) (*egressgatewayspidernetiov1.EgressGateway, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(egressgatewaysResource, "status", egressGateway), &egressgatewayspidernetiov1.EgressGateway{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGateway), err
}

// Delete takes name of the egressGateway and deletes it. Returns an error if one occurs.
func (c *FakeEgressGateways) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(egressgatewaysResource, name, opts), &egressgatewayspidernetiov1.EgressGateway{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEgressGateways) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(egressgatewaysResource, listOpts)

	_, err := c.Fake.Invokes(action, &egressgatewayspidernetiov1.EgressGatewayList{})
	return err
}

// Patch applies the patch and returns the patched egressGateway.
func (c *FakeEgressGateways) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *egressgatewayspidernetiov1.EgressGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(egressgatewaysResource, name, pt, data, subresources...), &egressgatewayspidernetiov1.EgressGateway{})
	if obj == nil {
		return nil, err
	}
	return obj.(*egressgatewayspidernetiov1.EgressGateway), err
}
