// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/spidernet-io/egressgateway/pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeEgressgatewayV1 struct {
	*testing.Fake
}

func (c *FakeEgressgatewayV1) EgressGatewayNodes() v1.EgressGatewayNodeInterface {
	return &FakeEgressGatewayNodes{c}
}

func (c *FakeEgressgatewayV1) EgressGatewayPolicies() v1.EgressGatewayPolicyInterface {
	return &FakeEgressGatewayPolicies{c}
}

func (c *FakeEgressgatewayV1) EgressNodes() v1.EgressNodeInterface {
	return &FakeEgressNodes{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeEgressgatewayV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
