// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/spidernet-io/egressgateway/pkg/k8s/apis/egressgateway.spidernet.io/v1"
	scheme "github.com/spidernet-io/egressgateway/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EgressGatewayNodesGetter has a method to return a EgressGatewayNodeInterface.
// A group's client should implement this interface.
type EgressGatewayNodesGetter interface {
	EgressGatewayNodes() EgressGatewayNodeInterface
}

// EgressGatewayNodeInterface has methods to work with EgressGatewayNode resources.
type EgressGatewayNodeInterface interface {
	Create(ctx context.Context, egressGatewayNode *v1.EgressGatewayNode, opts metav1.CreateOptions) (*v1.EgressGatewayNode, error)
	Update(ctx context.Context, egressGatewayNode *v1.EgressGatewayNode, opts metav1.UpdateOptions) (*v1.EgressGatewayNode, error)
	UpdateStatus(ctx context.Context, egressGatewayNode *v1.EgressGatewayNode, opts metav1.UpdateOptions) (*v1.EgressGatewayNode, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.EgressGatewayNode, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EgressGatewayNodeList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressGatewayNode, err error)
	EgressGatewayNodeExpansion
}

// egressGatewayNodes implements EgressGatewayNodeInterface
type egressGatewayNodes struct {
	client rest.Interface
}

// newEgressGatewayNodes returns a EgressGatewayNodes
func newEgressGatewayNodes(c *EgressgatewayV1Client) *egressGatewayNodes {
	return &egressGatewayNodes{
		client: c.RESTClient(),
	}
}

// Get takes name of the egressGatewayNode, and returns the corresponding egressGatewayNode object, and an error if there is any.
func (c *egressGatewayNodes) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EgressGatewayNode, err error) {
	result = &v1.EgressGatewayNode{}
	err = c.client.Get().
		Resource("egressgatewaynodes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EgressGatewayNodes that match those selectors.
func (c *egressGatewayNodes) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EgressGatewayNodeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EgressGatewayNodeList{}
	err = c.client.Get().
		Resource("egressgatewaynodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested egressGatewayNodes.
func (c *egressGatewayNodes) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("egressgatewaynodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a egressGatewayNode and creates it.  Returns the server's representation of the egressGatewayNode, and an error, if there is any.
func (c *egressGatewayNodes) Create(ctx context.Context, egressGatewayNode *v1.EgressGatewayNode, opts metav1.CreateOptions) (result *v1.EgressGatewayNode, err error) {
	result = &v1.EgressGatewayNode{}
	err = c.client.Post().
		Resource("egressgatewaynodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressGatewayNode).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a egressGatewayNode and updates it. Returns the server's representation of the egressGatewayNode, and an error, if there is any.
func (c *egressGatewayNodes) Update(ctx context.Context, egressGatewayNode *v1.EgressGatewayNode, opts metav1.UpdateOptions) (result *v1.EgressGatewayNode, err error) {
	result = &v1.EgressGatewayNode{}
	err = c.client.Put().
		Resource("egressgatewaynodes").
		Name(egressGatewayNode.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressGatewayNode).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *egressGatewayNodes) UpdateStatus(ctx context.Context, egressGatewayNode *v1.EgressGatewayNode, opts metav1.UpdateOptions) (result *v1.EgressGatewayNode, err error) {
	result = &v1.EgressGatewayNode{}
	err = c.client.Put().
		Resource("egressgatewaynodes").
		Name(egressGatewayNode.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressGatewayNode).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the egressGatewayNode and deletes it. Returns an error if one occurs.
func (c *egressGatewayNodes) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("egressgatewaynodes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *egressGatewayNodes) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("egressgatewaynodes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched egressGatewayNode.
func (c *egressGatewayNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressGatewayNode, err error) {
	result = &v1.EgressGatewayNode{}
	err = c.client.Patch(pt).
		Resource("egressgatewaynodes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
