// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/spidernet-io/egressgateway/pkg/k8s/apis/egressgateway.spidernet.io/v1"
	scheme "github.com/spidernet-io/egressgateway/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EgressNodesGetter has a method to return a EgressNodeInterface.
// A group's client should implement this interface.
type EgressNodesGetter interface {
	EgressNodes() EgressNodeInterface
}

// EgressNodeInterface has methods to work with EgressNode resources.
type EgressNodeInterface interface {
	Create(ctx context.Context, egressNode *v1.EgressNode, opts metav1.CreateOptions) (*v1.EgressNode, error)
	Update(ctx context.Context, egressNode *v1.EgressNode, opts metav1.UpdateOptions) (*v1.EgressNode, error)
	UpdateStatus(ctx context.Context, egressNode *v1.EgressNode, opts metav1.UpdateOptions) (*v1.EgressNode, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.EgressNode, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EgressNodeList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressNode, err error)
	EgressNodeExpansion
}

// egressNodes implements EgressNodeInterface
type egressNodes struct {
	client rest.Interface
}

// newEgressNodes returns a EgressNodes
func newEgressNodes(c *EgressgatewayV1Client) *egressNodes {
	return &egressNodes{
		client: c.RESTClient(),
	}
}

// Get takes name of the egressNode, and returns the corresponding egressNode object, and an error if there is any.
func (c *egressNodes) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EgressNode, err error) {
	result = &v1.EgressNode{}
	err = c.client.Get().
		Resource("egressnodes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EgressNodes that match those selectors.
func (c *egressNodes) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EgressNodeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EgressNodeList{}
	err = c.client.Get().
		Resource("egressnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested egressNodes.
func (c *egressNodes) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("egressnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a egressNode and creates it.  Returns the server's representation of the egressNode, and an error, if there is any.
func (c *egressNodes) Create(ctx context.Context, egressNode *v1.EgressNode, opts metav1.CreateOptions) (result *v1.EgressNode, err error) {
	result = &v1.EgressNode{}
	err = c.client.Post().
		Resource("egressnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressNode).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a egressNode and updates it. Returns the server's representation of the egressNode, and an error, if there is any.
func (c *egressNodes) Update(ctx context.Context, egressNode *v1.EgressNode, opts metav1.UpdateOptions) (result *v1.EgressNode, err error) {
	result = &v1.EgressNode{}
	err = c.client.Put().
		Resource("egressnodes").
		Name(egressNode.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressNode).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *egressNodes) UpdateStatus(ctx context.Context, egressNode *v1.EgressNode, opts metav1.UpdateOptions) (result *v1.EgressNode, err error) {
	result = &v1.EgressNode{}
	err = c.client.Put().
		Resource("egressnodes").
		Name(egressNode.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressNode).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the egressNode and deletes it. Returns an error if one occurs.
func (c *egressNodes) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("egressnodes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *egressNodes) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("egressnodes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched egressNode.
func (c *egressNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressNode, err error) {
	result = &v1.EgressNode{}
	err = c.client.Patch(pt).
		Resource("egressnodes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
