// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/spidernet-io/egressgateway/pkg/k8s/apis/egressgateway.spidernet.io/v1"
	scheme "github.com/spidernet-io/egressgateway/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EgressGatewayRulesGetter has a method to return a EgressGatewayRuleInterface.
// A group's client should implement this interface.
type EgressGatewayRulesGetter interface {
	EgressGatewayRules() EgressGatewayRuleInterface
}

// EgressGatewayRuleInterface has methods to work with EgressGatewayRule resources.
type EgressGatewayRuleInterface interface {
	Create(ctx context.Context, egressGatewayRule *v1.EgressGatewayRule, opts metav1.CreateOptions) (*v1.EgressGatewayRule, error)
	Update(ctx context.Context, egressGatewayRule *v1.EgressGatewayRule, opts metav1.UpdateOptions) (*v1.EgressGatewayRule, error)
	UpdateStatus(ctx context.Context, egressGatewayRule *v1.EgressGatewayRule, opts metav1.UpdateOptions) (*v1.EgressGatewayRule, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.EgressGatewayRule, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EgressGatewayRuleList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressGatewayRule, err error)
	EgressGatewayRuleExpansion
}

// egressGatewayRules implements EgressGatewayRuleInterface
type egressGatewayRules struct {
	client rest.Interface
}

// newEgressGatewayRules returns a EgressGatewayRules
func newEgressGatewayRules(c *EgressgatewayV1Client) *egressGatewayRules {
	return &egressGatewayRules{
		client: c.RESTClient(),
	}
}

// Get takes name of the egressGatewayRule, and returns the corresponding egressGatewayRule object, and an error if there is any.
func (c *egressGatewayRules) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EgressGatewayRule, err error) {
	result = &v1.EgressGatewayRule{}
	err = c.client.Get().
		Resource("egressgatewayrules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EgressGatewayRules that match those selectors.
func (c *egressGatewayRules) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EgressGatewayRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EgressGatewayRuleList{}
	err = c.client.Get().
		Resource("egressgatewayrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested egressGatewayRules.
func (c *egressGatewayRules) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("egressgatewayrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a egressGatewayRule and creates it.  Returns the server's representation of the egressGatewayRule, and an error, if there is any.
func (c *egressGatewayRules) Create(ctx context.Context, egressGatewayRule *v1.EgressGatewayRule, opts metav1.CreateOptions) (result *v1.EgressGatewayRule, err error) {
	result = &v1.EgressGatewayRule{}
	err = c.client.Post().
		Resource("egressgatewayrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressGatewayRule).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a egressGatewayRule and updates it. Returns the server's representation of the egressGatewayRule, and an error, if there is any.
func (c *egressGatewayRules) Update(ctx context.Context, egressGatewayRule *v1.EgressGatewayRule, opts metav1.UpdateOptions) (result *v1.EgressGatewayRule, err error) {
	result = &v1.EgressGatewayRule{}
	err = c.client.Put().
		Resource("egressgatewayrules").
		Name(egressGatewayRule.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressGatewayRule).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *egressGatewayRules) UpdateStatus(ctx context.Context, egressGatewayRule *v1.EgressGatewayRule, opts metav1.UpdateOptions) (result *v1.EgressGatewayRule, err error) {
	result = &v1.EgressGatewayRule{}
	err = c.client.Put().
		Resource("egressgatewayrules").
		Name(egressGatewayRule.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressGatewayRule).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the egressGatewayRule and deletes it. Returns an error if one occurs.
func (c *egressGatewayRules) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("egressgatewayrules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *egressGatewayRules) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("egressgatewayrules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched egressGatewayRule.
func (c *egressGatewayRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressGatewayRule, err error) {
	result = &v1.EgressGatewayRule{}
	err = c.client.Patch(pt).
		Resource("egressgatewayrules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
