name: Call Release Pages

env:
  MERGE_BRANCH: github_pages
  PR_LABEL: pr/robot_update
  PR_REVIEWER: lou-lan

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
  # --- call by manual
  workflow_dispatch:
    inputs:
      ref:
        description: 'branch, tag, sha'
        required: true
        default: main

permissions: write-all

jobs:
  package:
    name: prepare
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ env.RUN_REF }}
      skip_all_job: ${{ env.SKIP_ALL_JOB }}
    steps:
      - name: Get Ref
        id: get_ref
        run: |
          pwd
          ls
          if ${{ github.event_name == 'workflow_dispatch' }}; then
              echo "call by workflow_dispatch"
              echo "REF=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
          elif ${{ inputs.ref != '' }}; then
              echo "call by workflow_call"
              echo "REF=${{ inputs.ref }}" >> $GITHUB_ENV
          else
              echo "unexpected event: ${{ github.event_name }}"
              exit 1
          fi

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.REF }}

      - name: Set main branch docs to dev (latest)
        id: main_docs
        if: ${{ env.REF == 'main' }}
        run: |
          pip install mkdocs==1.5.2 mike==1.1.2 mkdocs-material==9.2.8 mkdocs-static-i18n==1.0.2
          git config user.email "robot@example.com"
          git config user.name "robot"
          cp ./docs/mkdocs.yml ./
          mike deploy --rebase -b ${{ env.MERGE_BRANCH }} dev -t "dev (${{ env.REF }})"
          rm -rf ./site && rm -rf ./mkdocs.yml
          git checkout -f ${{ env.MERGE_BRANCH }}
          rm -rf ./charts && rm -rf ./index.yaml && rm -rf ./changelogs
          tar -czvf ./site.tar.gz *
          ls
          echo "push document version `dev` from branch ${{ env.REF }}."

      - name: Extract Version
        id: extract
        if: ${{ env.REF != 'main' }}
        run: |
          if ! grep -E "^[[:space:]]*v[0-9]+.[0-9]+.[0-9]+[[:space:]]*$" VERSION &>/dev/null ; then
            echo "not a release version, skip generating doc."
            cat VERSION
            echo "SKIP_ALL_JOB=true" >> $GITHUB_ENV
            exit 0
          fi
          # for example v0.6.1, the build's documentation version is v0.6
          docVersion=` cat VERSION  | tr -d ' ' | tr -d '\n' | grep -Eo "v[0-9]+\.[0-9]+" `
          if [ -n "${docVersion}" ]; then
              echo "the version intercepted from the branch is: ${docVersion}"
          else
              echo "error, failed to get version." && exit 1
          fi
          git checkout -f ${{ env.MERGE_BRANCH }}
          echo "Switch to the branch:${{ env.MERGE_BRANCH }} where the document is located"
          ls
          if [ -e "${docVersion}" ]; then
              echo "doc version:${docVersion} already exists, just update it."
              echo "SET_LATEST=false" >> $GITHUB_ENV
          else
              echo "The doc version:${docVersion} does not exist yet, while generating the doc and set it to latest"
              echo "SET_LATEST=true" >> $GITHUB_ENV
          fi
          echo "the doc version is: ${docVersion}"
          echo "DOCS_TAG=${docVersion}" >> $GITHUB_ENV

      - name: build doc site
        id: build_doc
        if: ${{ env.SKIP_ALL_JOB != 'true' && env.REF != 'main' }}
        run: |
          git checkout ${{ env.REF }}
          ls
          echo "switch to the release version branch ${{ env.REF }}"
          pip install mkdocs==1.5.2 mike==1.1.2 mkdocs-material==9.2.8 mkdocs-static-i18n==1.0.2
          git config user.email "robot@example.com"
          git config user.name "robot"
          cp ./docs/mkdocs.yml ./
          if ${{ env.SET_LATEST == 'true' }} ;then
              echo "generate doc version:${{ env.DOCS_TAG }} and set to latest."
              mike deploy --rebase -b ${{ env.MERGE_BRANCH }} --update-aliases ${{env.DOCS_TAG }} latest
              mike set-default -b ${{ env.MERGE_BRANCH }} latest
          else
              echo "the version:${{ env.DOCS_TAG }} of the doc does not need to be set to the latest."
              mike deploy --rebase -b ${{ env.MERGE_BRANCH }} ${{ env.DOCS_TAG }}
          fi
          rm -rf ./site
          rm -rf ./mkdocs.yml
          git checkout -f  ${{ env.MERGE_BRANCH }}
          rm -rf ./charts && rm -rf ./index.yaml && rm -rf ./changelogs
          tar -czvf ./site.tar.gz *
          ls
          echo "Automatic release, offline doc site package ready"
          echo "Push a doc version: ${{ env.DOCS_TAG }} from branch: ${{ env.REF }}, update it to latest: ${{ env.SET_LATEST }} "

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        if: ${{ env.SKIP_ALL_JOB != 'true' }}
        with:
          name: site_artifact
          path: site.tar.gz
          retention-days: 0
          if-no-files-found: error

  create_pr:
    name: Create PR
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.MERGE_BRANCH }}
          fetch-depth: 0

      ## doc
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.2
        if: ${{ needs.package.outputs.skip_all_job != 'true' }}
        with:
          name: site_artifact

      - name: Untar Doc
        if: ${{ needs.package.outputs.skip_all_job != 'true' }}
        run: |
          tar -xzvf site.tar.gz
          rm -f site.tar.gz

      # Allow auto-merge on general
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: "robot update website from ${{ needs.package.outputs.REF }} to branch ${{ env.MERGE_BRANCH }} "
          commit-message: "robot update website from  ${{ needs.package.outputs.REF }} to branch ${{ env.MERGE_BRANCH }} "
          branch-suffix: timestamp
          branch: robot/update_doc
          delete-branch: true
          base: ${{ env.MERGE_BRANCH }}
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.PR_LABEL }}
          reviewers: ${{ env.PR_REVIWER }}
