name: 'Helm'

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'charts/values.yaml'

permissions: write-all

jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bitnami-labs/readme-generator-for-helm
        uses: actions/checkout@v3
        with:
          repository: 'bitnami-labs/readme-generator-for-helm'
          ref: '56339fd97199c76326f224272deba14f3bcc8c3f'
          path: readme-generator-for-helm

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('readme-generator-for-helm/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install readme-generator-for-helm
        run: |
          cd readme-generator-for-helm
          npm install

      - name: Checkout egressgateway project
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          path: thisProject

      - name: Diff chart/README.md
        id: execute
        run: |
          echo "Diff chart/README.md"
          echo "-----------------------------"
          readme-generator-for-helm/bin/index.js \
          --values "thisProject/charts/values.yaml" \
          --readme "thisProject/charts/README.md"
          
          echo "-----------------------------"
          cat thisProject/charts/README.md
